---
title: "CKS as a tool for biocultural stewardship: A global review"
format: 
  html:
    embed-resources: true
editor: source
execute:
  message: false
  warning: false
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(here)
library(readxl)
```

Examine the data, both linear and log transformed (to examine exponential growth)
```{r}
lit_data <- read_excel(here('data/RawData_Figure2_PAN.xlsx')) %>%
  janitor::clean_names() %>%
  filter(!is.na(year)) %>%
  complete(year = 1994:2022, fill = list(docs = 0)) %>%
  rename(group_3 = group) %>%
  mutate(year94 = year - 1994,
         year03 = ifelse(year >= 2003, year - 2003, NA),
         year16 = ifelse(year >= 2016, year - 2016, NA))

```

### linear models

First, with all years; second, excluding 1994
```{r}
lm94 <- lm(total ~ year94, data = lit_data)
broom::tidy(lm94)

lm03 <- lm(total ~ year03, data = lit_data)
broom::tidy(lm03)

lm16 <- lm(total ~ year16, data = lit_data)
broom::tidy(lm16)
```

### log linear models

```{r}
loglm94 <- lm(log(total) ~ year94, data = lit_data %>% filter(total > 0))
broom::tidy(loglm94)

loglm03 <- lm(log(total) ~ year03, data = lit_data)
broom::tidy(loglm03)

loglm16 <- lm(log(total) ~ year16, data = lit_data)
broom::tidy(loglm16)
```

## Final plots?

```{r}
brks_lbls <- lit_data %>%
  filter(year %% 5 == 0)

palette <-  rgb(c(65, 102, 35), c(174, 194, 139), c(118, 164, 69), 
                maxColorValue = 255) %>%
  rev()


exp_fxn <- function(x, mdl) {
  exp(x * mdl$coefficients[2] + mdl$coefficients[1])
}

plot_df <- lit_data %>%
  pivot_longer(names_to = 'group', values_to = 'docs', cols = starts_with('group')) %>%
  mutate(docs = ifelse(is.na(docs), 0, docs)) %>%
  mutate(group = str_replace(str_to_title(group), '_', ' '),
         group = str_replace(group, '3', '*'),
         group = factor(group, levels = c('Group 1', 'Group 2', 'Group *')))

ggplot(plot_df, aes(x = year94, y = docs, fill = group)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  scale_fill_manual(values = palette) +
  geom_function(fun = exp_fxn, args = list(mdl = loglm94), color = 'darkred') +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = brks_lbls$year94, labels = brks_lbls$year, expand = c(0, 0.25)) +
  scale_y_continuous(limits = c(0, 34), expand = c(0, 0), position = 'right') +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        axis.title.y.right = element_text(margin = margin(l = 10)),
        legend.position = c(.31, .76)) +
  labs(x = 'Year of publication', y = 'Number of documents', fill = '')
ggplot(plot_df, aes(x = year03, y = docs, fill = group)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  scale_fill_manual(values = palette) +
  geom_function(fun = exp_fxn, args = list(mdl = loglm03), color = 'darkred') +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = brks_lbls$year03, labels = brks_lbls$year, expand = c(0, 0.25)) +
  scale_y_continuous(limits = c(0, 34), expand = c(0, 0), position = 'right') +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        axis.title.y.right = element_text(margin = margin(l = 10)),
        legend.position = c(.25, .76)) +
  labs(x = 'Year of publication', y = 'Number of documents', fill = '')

```

